#generate:
#  db:
#    name: SeBaFi_Ultra_Dev
#    password: 123457
#    username: SeBaFi_Ultra_Dev
#    tablename: user_question
#    url: jdbc:mysql://172.16.3.80:3306/SeBaFi_Ultra_Dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC


spring:
  profiles:
    active: dev
  freemarker:
    request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ #模板加载路径 按需配置
    charset: UTF-8 #编码格式
    settings:
      number_format: '0.##'   #数字格式化，无小数点
    #  quartz:
    #    # quartz 相关属性配置
    #    properties:
    #      org:
    #        quartz:
    #          scheduler:
    #            instanceName: ttmScheduler
    #            instanceId: AUTO
    #          jobStore:
    #            class: org.quartz.impl.jdbcjobstore.JobStoreTX
    #            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
    #            tablePrefix: QRTZ_
    #            isClustered: true
    #            clusterCheckinInterval: 10000
    #            useProperties: false
    #            dataSource: quartzDataSource
    #            acquireTriggersWithinLock: true
    #          threadPool:
    #            class: org.quartz.simpl.SimpleThreadPool
    #            threadCount: 90 # 开启90个线程
    #            threadPriority: 5
    #            threadsInheritContextClassLoaderOfInitializingThread: true
    #          dataSource:
    #            quartzDataSource:
    #              connectionProvider:
    #                class: com.hangmindamei.ttm.ttm.configuration.quartz.SpringConnectionProvider
    #数据库方式
    job-store-type: jdbc

datasource:
  username: root
  password: 123456
  url: jdbc:mysql://121.0.0.1:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
  driverclassname: com.mysql.cj.jdbc.Driver


#  datasource:
#    databasews:
#      username: root
#      password: 123456
#      url: jdbc:mysql://121.5.73.211:3306/quartz?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      driverclassname: com.mysql.cj.jdbc.Driver
#    databasexr:
#      username: root
#      password: 123456
#      url: jdbc:mysql://121.4.88.76:3306/ws?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      driverclassname: com.mysql.cj.jdbc.Driver
#    databasekk:
#      username: root
#      password: 123456
#      url: jdbc:mysql://106.54.87.93:3306/ws?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
#      driverclassname: com.mysql.cj.jdbc.Driver
#    jpa:
#      database: mysql
#      show-sql: true
#      hibernate:
#        ddl-auto: update
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      database-platform: org.hibernate.dialect.MySQL5Dialect

  ## Redis 配置
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    ## Redis服务器连接端口
    port: 6379
    lettuce:
      pool:
        max-active: 64
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 12000


server:
  port: 80

logging:
  level:
    com.spring.ws.spring.dao: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


